In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import mutual_info_classif

In [2]:
adult_census_income_data=pd.read_csv("adult.csv")

In [3]:
adult_census_income_data.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [4]:
adult_census_income_data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [5]:
adult_census_income_data['workclass'].value_counts()

workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

In [6]:
adult_census_income_data['workclass'].mode()

0    Private
Name: workclass, dtype: str

In [7]:
adult_census_income_data['workclass']=adult_census_income_data['workclass'].replace('?','Private')

In [8]:
adult_census_income_data['occupation'].value_counts()

occupation
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3770
Sales                3650
Other-service        3295
Machine-op-inspct    2002
?                    1843
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: count, dtype: int64

In [9]:
adult_census_income_data['occupation'].mode()

0    Prof-specialty
Name: occupation, dtype: str

In [10]:
adult_census_income_data['occupation']=adult_census_income_data['occupation'].replace('?','Prof-specialty')

In [11]:
adult_census_income_data.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,Private,77053,HS-grad,9,Widowed,Prof-specialty,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,Private,186061,Some-college,10,Widowed,Prof-specialty,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [22]:
adult_census_income_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

In [33]:
from sklearn.preprocessing import LabelEncoder

X = adult_census_income_data.drop('income', axis=1)
y = adult_census_income_data['income']

# Encode target
y = y.map({'<=50K':0, '>50K':1})

# Encode categorical features
cat_cols = X.select_dtypes(include='str').columns

le = LabelEncoder()
for col in cat_cols:
    X[col] = le.fit_transform(X[col])

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

# Compute MI
mi = mutual_info_classif(x_train, y_train, discrete_features=True)

# View scores
mi_series = pd.Series(mi, index=X.columns).sort_values(ascending=False)
print(mi_series)

fnlwgt            0.422510
relationship      0.115363
marital.status    0.109033
capital.gain      0.083500
age               0.068839
education         0.066526
education.num     0.066526
occupation        0.051466
hours.per.week    0.043756
capital.loss      0.037463
sex               0.025397
workclass         0.012357
native.country    0.006219
race              0.005614
dtype: float64

In [173]:
from sklearn.feature_selection import SelectKBest
sel_ten_cols=SelectKBest(mutual_info_classif, k=7)
sel_ten_cols.fit(x_train, y_train)
# 1. Get the list of selected column names
selected_cols = x_train.columns[sel_ten_cols.get_support()]

# 2. Filter x_train and x_test to retain only these columns
x_train_filtered = x_train[selected_cols]
x_test_filtered = x_test[selected_cols]

# Optional: Verify the new shapes
print(x_train_filtered.shape) # Output: (n_samples, 10)

(22792, 7)

In [174]:
x_train_filtered.columns

Index(['age', 'education', 'education.num', 'marital.status', 'occupation',
       'relationship', 'capital.gain'],
      dtype='str')

In [175]:
x_train_filtered.head()

,age,education,education.num,marital.status,occupation,relationship,capital.gain
32098,40,9,13,2,3,5,0
25206,39,11,9,2,6,0,0
23491,42,15,10,4,3,1,0
12367,27,11,9,4,4,3,0
7054,38,12,14,2,3,0,0

In [176]:
from sklearn.linear_model import LogisticRegression

model=LogisticRegression(max_iter=10000,C=0.1,class_weight={0:1, 1:2})

In [177]:
model.fit(x_train_filtered,y_train)

LogisticRegression(C=0.1, class_weight={0: 1, 1: 2}, max_iter=10000)

In [178]:
y_preds=model.predict(x_test_filtered)

In [179]:
y_pred_probab=model.predict_proba(x_test_filtered)
y_pred_probab

array([[0.9850531 , 0.0149469 ],
       [0.95116137, 0.04883863],
       [0.8588901 , 0.1411099 ],
       ...,
       [0.91407045, 0.08592955],
       [0.94311399, 0.05688601],
       [0.45415603, 0.54584397]], shape=(9769, 2))

In [180]:
from sklearn.metrics import f1_score

f1_score=f1_score(y_test,y_preds,average='binary')

In [181]:
f1_score

0.5730431142737548

In [182]:
adult_census_income_data['income'].value_counts()

income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [183]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.87      0.86      0.86      7410
           1       0.57      0.58      0.57      2359

    accuracy                           0.79      9769
   macro avg       0.72      0.72      0.72      9769
weighted avg       0.79      0.79      0.79      9769

In [184]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_preds)

array([[6360, 1050],
       [ 990, 1369]])

In [209]:
y_prob=y_pred_probab[:,1]
treshold=0.7
y_pred_custom=(y_prob>=treshold).astype(int)

In [210]:
print(classification_report(y_test, y_pred_custom))

              precision    recall  f1-score   support

           0       0.82      0.95      0.88      7410
           1       0.71      0.36      0.48      2359

    accuracy                           0.81      9769
   macro avg       0.77      0.66      0.68      9769
weighted avg       0.80      0.81      0.79      9769

In [203]:
for t in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9]:
    y_pred = (y_prob >= t).astype(int)
    p = precision_score(y_test, y_pred)
    r = recall_score(y_test, y_pred)
    print(f"{t} → Precision: {p:.3f}, Recall: {r:.3f}")

0.5 → Precision: 0.566, Recall: 0.580
0.6 → Precision: 0.644, Recall: 0.475
0.7 → Precision: 0.712, Recall: 0.359
0.8 → Precision: 0.795, Recall: 0.243
0.85 → Precision: 0.879, Recall: 0.193
0.9 → Precision: 0.934, Recall: 0.156

In [204]:
from sklearn.metrics import precision_score, recall_score

for t in [0.5, 0.6, 0.7, 0.8, 0.85, 0.9]:
    y_pred = (y_prob >= t).astype(int)
    p = precision_score(y_test, y_pred)
    r = recall_score(y_test, y_pred)
    print(f"{t} → Precision: {p:.3f}, Recall: {r:.3f}")

0.5 → Precision: 0.566, Recall: 0.580
0.6 → Precision: 0.644, Recall: 0.475
0.7 → Precision: 0.712, Recall: 0.359
0.8 → Precision: 0.795, Recall: 0.243
0.85 → Precision: 0.879, Recall: 0.193
0.9 → Precision: 0.934, Recall: 0.156

In [254]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled= scaler.fit_transform(x_train_filtered)
x_test_scaled= scaler.transform(x_test_filtered)

In [439]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=300, random_state=42,class_weight='balanced',min_samples_split=5,
                             min_samples_leaf=3,max_features='log2',max_depth=8)
clf.fit(x_train_scaled, y_train)

# Predict and evaluate
y_pred = clf.predict(x_test_scaled)

In [440]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.76      0.84      7410
           1       0.54      0.86      0.66      2359

    accuracy                           0.79      9769
   macro avg       0.74      0.81      0.75      9769
weighted avg       0.85      0.79      0.80      9769

In [441]:
y_pred_prob=clf.predict_proba(x_test_scaled)
y_prob1=y_pred_prob[:,1]
treshold=0.7
y_pred_custom=(y_prob1>=treshold).astype(int)

In [442]:
print(classification_report(y_test, y_pred_custom))

              precision    recall  f1-score   support

           0       0.88      0.93      0.90      7410
           1       0.73      0.61      0.66      2359

    accuracy                           0.85      9769
   macro avg       0.80      0.77      0.78      9769
weighted avg       0.84      0.85      0.85      9769

In [434]:
from sklearn.model_selection import RandomizedSearchCV

params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

rf = RandomForestClassifier(class_weight='balanced', random_state=42)

search = RandomizedSearchCV(
    rf,
    param_distributions=params,
    n_iter=10,
    scoring='f1',
    cv=3,
    n_jobs=-1
)

search.fit(x_train_filtered, y_train)

best_model = search.best_estimator_

In [231]:
best_model

RandomForestClassifier(class_weight='balanced', max_features='log2',
                       min_samples_leaf=4, min_samples_split=10,
                       n_estimators=300, random_state=42)

In [244]:
y_prob = best_model.predict_proba(x_test_filtered)[:,1]
treshold=0.7
y_pred_custom1=(y_prob>=treshold).astype(int)

In [245]:
print(classification_report(y_test,y_pred_custom1))

              precision    recall  f1-score   support

           0       0.88      0.92      0.90      7410
           1       0.72      0.61      0.66      2359

    accuracy                           0.85      9769
   macro avg       0.80      0.77      0.78      9769
weighted avg       0.84      0.85      0.85      9769

In [241]:
y_train_pred=best_model.predict_proba(x_train_filtered)[:,1]
treshold=0.7
y_pred_custom2=(y_train_pred>=treshold).astype(int)
print(classification_report(y_train,y_pred_custom2))

              precision    recall  f1-score   support

           0       0.90      0.94      0.92     17310
           1       0.78      0.67      0.72      5482

    accuracy                           0.87     22792
   macro avg       0.84      0.80      0.82     22792
weighted avg       0.87      0.87      0.87     22792